trigger:
- Development

pool:
  vmImage: 'ubuntu-latest'

variables:
- group: dev-dealgo-backend  # Reference the variable group

stages:
  - stage: Build
    displayName: Build and Push Docker Image
    jobs:
      - job: Build
        displayName: Build and Push Docker Image
        steps:
          - task: Docker@2
            displayName: Build and Push Docker image
            inputs:
              containerRegistry: 'acrbackenddev-1274'
              repository: '$(REPO_NAME)'
              command: 'buildAndPush'
              Dockerfile: '$(DOCKERFILE_PATH)'
              tags: '$(IMAGE_TAG)'
            condition: succeeded()

  - stage: Deploy
    displayName: Deploy to Azure App Service
    dependsOn: Build
    jobs:
      - job: Deploy
        displayName: Deploy to Azure App Service
        steps:
        # - task: AzureWebApp@1
        #   displayName: 'Deploy to Azure App Service'
        #   inputs:
        #     azureSubscription: '$(APP_SERVICE_CONNECTION)'
        #     appName: '$(APP_SERVICE_NAME)'
        #     package: '$(REPO_NAME):$(IMAGE_TAG)'
        #     deploymentMethod: 'containerImage'
        #     enableCustomDeployment: true
        - task: AzureRmWebAppDeployment@4 
          inputs:
            ConnectionType: 'AzureRM'
            azureSubscription: '$(APP_SERVICE_CONNECTION)'
            appType: 'webAppContainer'
            WebAppName: '$(APP_SERVICE_NAME)'
            DockerNamespace: '$(ACR_LOGIN_SERVER)'
            DockerRepository: '$(APP_SERVICE_NAME):$(IMAGE_TAG)'
            DockerImageTag: '$(Build.BuildNumber).$(Build.BuildId)'
            