# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- Development

pool:
  vmImage: ubuntu-latest

steps:
- task: Docker@2
  displayName: 'Build Docker image'
  inputs:
    command: build
    dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
    tags: 'dealgostore.azurecr.io/myimage:$(Build.BuildId)'

- task: Docker@2
  displayName: 'Push Docker image'
  inputs:
    command: push
    repository: 'dealgostore.azurecr.io/myimage'
    tags: '$(Build.BuildId)'
    containerRegistry: 'dealgostore'
