trigger:
- Development

pool:
  vmImage: 'ubuntu-latest'

variables:
  # Azure Container Registry connection established during pipeline creation
  acrName: 'acrbackend'
  acrResourceGroup: 'SC-RG-APP-DEV'
  imageRepository: 'dealgo-backend'
  containerRegistry: '${acrName}.azurecr.io'
  dockerfilePath: '$(Build.SourcesDirectory)/docker/7.4/Dockerfile'
  dockerfilePath2: '**/Dockerfile'
  azureSubscription: 'b4e3d68f-20ee-447d-898b-4e40e6915fe0'
  tag: '$(Build.BuildNumber)'
  # dockerfilePath: './docker/7.4/Dockerfile'
  buildContext: './'

stages:
- stage: Build
  displayName: Build Docker image
  jobs:
  - job: Build
    displayName: Build Docker image
    steps:
    - script: |
        docker build -f $(dockerfilePath2) \
        --label com.azure.dev.image.system.teamfoundationcollectionuri=$(System.TeamFoundationCollectionUri) \
        --label com.azure.dev.image.system.teamproject=$(System.TeamProject) \
        --label com.azure.dev.image.build.repository.name=$(imageRepository) \
        --label com.azure.dev.image.build.sourceversion=$(Build.SourceVersion) \
        --label com.azure.dev.image.build.repository.uri=$(Build.Repository.Uri) \
        --label com.azure.dev.image.build.sourcebranchname=$(Build.SourceBranchName) \
        --label com.azure.dev.image.build.definitionname=$(Build.DefinitionName) \
        --label com.azure.dev.image.build.buildnumber=$(Build.BuildNumber) \
        --label com.azure.dev.image.build.builduri=$(Build.BuildUri) \
        --label image.base.ref.name=php:7.4-fpm-alpine \
        --label image.base.digest=sha256:0aeb129a60daff2874c5c70fcd9d88cdf3015b4fb4cc7c3f1a32a21e84631036 \
        -t $(imageRepository):$(Build.BuildId) -f $(dockerfilePath) .
      displayName: Build Docker image

    - task: Docker@2
      displayName: Build Docker image
      inputs:
        command: build
        Dockerfile: '**/Dockerfile'
        arguments: '-t $(imageRepository):$(Build.BuildId) -f $(dockerfilePath) .'
        # arguments: '-t $(imageName):$(tag) -f $(dockerfilePath) .'
        containerRegistry: $(acrName)
    
    - task: Docker@2
      displayName: Push Docker image to Azure Container Registry
      inputs:
        command: push
        repository: $(imageRepository)
        containerRegistry: $(acrName)

- stage: Deploy
  displayName: Deploy to Azure Web App
  dependsOn: Build
  jobs:
  - job: Deploy
    displayName: Deploy to Azure Web App
    steps:
    - task: AzureWebApp@1
      displayName: Azure Web App Deploy
      inputs:
        appType: webApp
        azureSubscription: $(acrResourceGroup)
        appName: 'dealgo-backend'
        package: $(imageRepository):$(Build.BuildId)
        deploymentMethod: 'containerRegistry'
        containerRegistryType: 'Azure Container Registry'
        dockerNamespace: $(acrName)
        dockerRegistryEndpoint: $(acrName).azurecr.io
        enableContinuousDeployment: true
        
