trigger:
- Development

pool:
  vmImage: 'ubuntu-latest'

variables:
- group: kv-dealgo-dev-group  # Reference the variable group

stages:
  - stage: Build
    displayName: Build and Push Docker Image
    jobs:
      - job: Build
        displayName: Build and Push Docker Image
        steps:
          - task: Docker@2
            displayName: Build and Push Docker image
            inputs:
              containerRegistry: 'acrdealgodev'
              repository: 'dealgo-backend-dev'
              command: 'buildAndPush'
              Dockerfile: './Dockerfile'
              tags: '$(Build.BuildNumber).$(Build.BuildId)'
            condition: succeeded()

# Deploy the Docker container to the Web App Service
  - stage: Deploy
    displayName: Deploy to Azure App Service
    dependsOn: Build
    jobs:
      - job: Deploy
        displayName: Deploy to Azure App Service
        steps:
        - task: AzureRmWebAppDeployment@4 
          inputs:
            ConnectionType: 'AzureRM'
            azureSubscription: 'SC-RG-APP-DEV-FREE'
            appType: 'webAppContainer'
            WebAppName: 'dealgo-backend-dev'
            DockerNamespace: '$(ACR-LOGIN-SERVER)'
            DockerRepository: '$(APP-SERVICE-NAME)'
            DockerImageTag: '$(Build.BuildNumber).$(Build.BuildId)'
            AppSettings: '-DB_PASSWORD $(DB-PASSWORD) -APP_KEY $(APP-KEY) -MAIL_PASSWORD $(MAIL-PASSWORD) -JWT_SECRET $(JWT_SECRET)'
            