trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  # Azure Container Registry connection established during pipeline creation
  acrName: 'acrbackend'
  acrResourceGroup: 'rg-app-dev'
  imageRepository: 'myimage'
  containerRegistry: '${acrName}.azurecr.io'
  dockerfilePath: '$(Build.SourcesDirectory)/docker/7.4/Dockerfile'

stages:
- stage: Build
  displayName: Build Docker image
  jobs:
  - job: Build
    displayName: Build Docker image
    steps:
    - task: Docker@2
      displayName: Build Docker image
      inputs:
        command: build
        arguments: '-t $(imageRepository):$(Build.BuildId) -f $(dockerfilePath) .'
        containerRegistry: $(acrName)
    - task: Docker@2
      displayName: Push Docker image to Azure Container Registry
      inputs:
        command: push
        repository: $(imageRepository)
        containerRegistry: $(acrName)

- stage: Deploy
  displayName: Deploy to Azure Web App
  dependsOn: Build
  jobs:
  - job: Deploy
    displayName: Deploy to Azure Web App
    steps:
    - task: AzureWebApp@1
      displayName: Azure Web App Deploy
      inputs:
        appType: webApp
        azureSubscription: 'mySubscription'
        appName: 'dealgo-backend'
        package: $(imageRepository):$(Build.BuildId)
        deploymentMethod: 'containerRegistry'
        containerRegistryType: 'Azure Container Registry'
        dockerNamespace: $(acrName)
        dockerRegistryEndpoint: $(acrName).azurecr.io
        enableContinuousDeployment: true
