trigger:
- Development

pool:
  vmImage: 'ubuntu-latest'

variables:
  # Azure Container Registry connection established during pipeline creation
  acrName: 'acrbackend'
  acrResourceGroup: 'SC-RG-APP-DEV'
  imageRepository: 'dealgo-backend'
  containerRegistry: '${acrName}.azurecr.io'
  dockerfilePath: '$(Build.SourcesDirectory)/docker/7.4/Dockerfile'
  dockerfilePath2: '**/Dockerfile'
  azureSubscription: 'b4e3d68f-20ee-447d-898b-4e40e6915fe0'

stages:
- stage: Build
  displayName: Build Docker image
  jobs:
  - job: Build
    displayName: Build Docker image
    steps:
    - task: Docker@2
      displayName: Build Docker image
      inputs:
        command: build
        Dockerfile: '**/Dockerfile'
        # arguments: '-t $(imageRepository):$(Build.BuildId) -f $(dockerfilePath) .'
        containerRegistry: $(acrName)
    
    - task: Docker@2
      displayName: Push Docker image to Azure Container Registry
      inputs:
        command: push
        repository: $(imageRepository)
        containerRegistry: $(acrName)

- stage: Deploy
  displayName: Deploy to Azure Web App
  dependsOn: Build
  jobs:
  - job: Deploy
    displayName: Deploy to Azure Web App
    steps:
    - task: AzureWebApp@1
      displayName: Azure Web App Deploy
      inputs:
        appType: webApp
        azureSubscription: $(acrResourceGroup)
        appName: 'dealgo-backend'
        package: $(imageRepository):$(Build.BuildId)
        deploymentMethod: 'containerRegistry'
        containerRegistryType: 'Azure Container Registry'
        dockerNamespace: $(acrName)
        dockerRegistryEndpoint: $(acrName).azurecr.io
        enableContinuousDeployment: true
        
