trigger:
- Development

pool:
  vmImage: 'ubuntu-latest'

variables:
- group: dev-dealgo-backend  # Reference the variable group

stages:
  - stage: Build
    displayName: Build and Push Docker Image
    jobs:
      - job: Build
        displayName: Build and Push Docker Image
        steps:
          - task: Docker@2
            displayName: Build and Push Docker image
            inputs:
              containerRegistry: '$(ACR_NAME)'
              repository: '$(IMAGE_NAME)'
              command: 'buildAndPush'
              Dockerfile: '$(DOCKERFILE_PATH)'
              tags: '$(IMAGE_TAG)'
            condition: succeeded()

  - stage: Deploy
    displayName: Deploy to Azure App Service
    dependsOn: Build
    jobs:
      - job: Deploy
        displayName: Deploy to Azure App Service
        steps:
        - task: AzureWebAppContainer@1
          displayName: Deploy to Azure Web App
          inputs:
            azureSubscription: '$(APP_SERVICE_CONNECTION)'
            appName: $(APP_SERVICE_NAME)
            imageName: $(IMAGE_NAME):$(IMAGE_TAG)