version: "3"
services:
  app:
    build:
      context: .
    ports:
      - "8000:9000"
    volumes:
      - .:/var/www/html
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - APP_KEY=your-app-key-here
      - DB_CONNECTION=mysql
      - DB_HOST=your-db-host-here
      - DB_PORT=3306
      - DB_DATABASE=your-db-name-here
      - DB_USERNAME=your-db-username-here
      - DB_PASSWORD=your-db-password-here